NOISSUE - Improve tests in users service
absmach/magistrala-old pull request #194
Opened 2023-12-20 12:05 UTC by 1998-felix

# What type of PR is this?

## What does this do?
Increase test coverage in users service and improves existing tests to match other packages.

## Which issue(s) does this PR fix/relate to?
None.

## Have you included tests for your changes?
No, since it is changes to the test file.

## Did you document any new/modified feature?
No,

### Notes

2023-12-27 13:31 UTC, rodneyosodo requested changes

2023-12-27 13:31 UTC, rodneyosodo commented on users/api/endpoint_test.go
> +	ts, cRepo, auth := usersSetup()
Generate service mocks and use them rather than using auth and repo mocks something like https://github.com/absmach/magistrala/blob/main/invitations/api/endpoint_test.go

2023-12-28 18:23 UTC, rodneyosodo requested changes

2023-12-28 18:23 UTC, rodneyosodo commented on users/postgres/clients_test.go
> +		},
Add where ID is empty

2023-12-28 18:23 UTC, rodneyosodo commented on users/postgres/clients_test.go
> +		},
Add more test cases something like https://github.com/absmach/magistrala/blob/main/invitations/postgres/invitations_test.go#L303C1-L637C3 also check the returned values

2024-01-03 12:00 UTC, dborovcanin requested changes

2024-01-03 12:00 UTC, dborovcanin commented on users/postgres/clients_test.go
> +		assert.Len(t, page.Clients, tc.len, fmt.Sprintf("%s: expected length %v, got %v", tc.desc, tc.len, len(page.Clients)))
Just like @rodneyosodo mentioned, please check values, not only length (`assert.ElementsMatch` or `assert.Equal`).

2024-01-04 13:19 UTC, rodneyosodo requested changes

2024-01-04 13:19 UTC, rodneyosodo commented on users/postgres/clients_test.go
> +
For `errors.ErrNotFound` change to

```go
rows, err := repo.ClientRepository.DB.NamedQueryContext(ctx, q, dbc)
if err != nil {
	return mgclients.Client{}, postgres.HandleError(repoerr.ErrViewEntity, err)
}
defer rows.Close()

dbc = pgclients.DBClient{}
if rows.Next() {
	if err = rows.StructScan(&dbc); err != nil {
		return mgclients.Client{}, postgres.HandleError(repoerr.ErrViewEntity, err)
	}

	client, err := pgclients.ToClient(dbc)
	if err != nil {
		return mgclients.Client{}, errors.Wrap(repoerr.ErrFailedOpDB, err)
	}

	return client, nil
}

return mgclients.Client{}, repoerr.ErrNotFound
```

since this code block is never ran

```go
if err == sql.ErrNoRows {
	return mgclients.Client{}, errors.Wrap(errors.ErrNotFound, err)
}
```

2024-01-04 13:19 UTC, rodneyosodo commented on users/postgres/clients_test.go
> +}
For Save add a cases where metadata is invalid i.e

```go
Metadata: map[string]interface{}{
	"key": make(chan int),
},
```

This can be used when querying too for failed cases

2024-01-04 13:19 UTC, rodneyosodo commented on users/postgres/clients_test.go
> +			desc: "retrieve invitations with limit",
```suggestion
			desc: "retrieve users with limit",
```

2024-01-04 13:19 UTC, rodneyosodo commented on users/postgres/clients_test.go
> +			desc: "retrieve with client name",
add invalid client name

2024-01-04 13:19 UTC, rodneyosodo commented on users/postgres/clients_test.go
> +			desc: "retrieve with status",
Add for disabled and all status

2024-01-04 13:19 UTC, rodneyosodo commented on users/service_test.go
> +	svc, cRepo, auth, _ := newService()
add cases where `selfRegister` is false

2024-01-04 13:19 UTC, rodneyosodo commented on users/service_test.go
> +	svc, cRepo, auth, _ := newService()
Add the following cases
- invalid role
- failed to add policies
- failed to do a policy rollback

2024-01-04 13:19 UTC, rodneyosodo commented on users/service_test.go
> +func newService() (users.Service, *mocks.Repository, *authmocks.Service, users.Emailer) {
Some functions are partially tested. Have a look at the test report and see the missing parts

2024-01-04 13:19 UTC, rodneyosodo commented on users/api/endpoint_test.go
> +
Also test for groups since some decode functions are in users package
- assignUsersEndpoint
- unassignUsersEndpoint
- assignGroupsEndpoint
- unassignGroupsEndpoint

2024-01-04 13:34 UTC, arvindh123 commented on users/service_test.go
>  		desc   string
Please try to add a case for save to failed in repository , Like some internal error / connection fails during `Save`

2024-01-04 13:40 UTC, arvindh123 commented on users/service_test.go
> +	svc, cRepo, auth, _ := newService()
Add case to retrieve clients as super Admin and normal user

2024-01-04 13:44 UTC, arvindh123 commented on users/service_test.go
Remove share list client case.

2024-01-04 13:47 UTC, arvindh123 commented on users/service_test.go
>  	cases := []struct {
Add repo call `CheckSuperAdmin` in RegisterClient, ViewClient, ListClients, UpdateClient, UpdateClientTags, UpdateClientIdentity the test cases

2024-01-04 13:48 UTC, arvindh123 commented on users/service_test.go
>  	wrongID      = testsutil.GenerateUUID(&testing.T{})
Add repo call `CheckSuperAdmin` in following function test cases :  RegisterClient, ViewClient, ListClients, UpdateClient, UpdateClientTags, UpdateClientIdentity

2024-01-04 13:48 UTC, arvindh123 commented on users/service_test.go
>  )
Each test case should have SuperAdmin and User cases

2024-01-04 14:11 UTC, arvindh123 commented on users/service_test.go
> +	svc, cRepo, auth, _ := newService()
Add Test case for
- disable client with normal user token
- User trying to do self disable

2024-01-12 09:07 UTC, rodneyosodo requested changes
There are some areas not covered with tests. Use this command to identify the missing cases and update accordingly

```bash
cd users && go test -tags test -v --race -covermode=atomic -coverprofile=cover.out ./... && go tool cover -html cover.out -o cover.html
```

2024-01-12 09:07 UTC, rodneyosodo commented on users/service_test.go
> +			desc:                    "list members with no policies successfully of the things kind",
Add a case for invalid token i.e identify fails

2024-01-12 09:07 UTC, rodneyosodo commented on users/service_test.go
> +
For this test there are some cases not covered especially when `pm.ListPerms` is true and `len(cp.Clients)>0`. Have a look at the test report and try and add the cases

2024-01-12 14:56 UTC, rodneyosodo requested changes

2024-01-12 14:56 UTC, rodneyosodo commented on users/api/endpoint_test.go
> +			status:      http.StatusInternalServerError,
As discussed remove the use of `StatusInternalServerError` and cover the missing cases

2024-01-12 14:56 UTC, rodneyosodo commented on users/postgres/clients_test.go
> +			desc: "add a client with invalid metadata",
Do this also for this PR https://github.com/absmach/magistrala-old/pull/200

2024-01-15 08:37 UTC, rodneyosodo requested changes

2024-01-15 08:37 UTC, rodneyosodo commented on users/api/endpoint_test.go
> +	}{
Add a case where the ID is empty

2024-01-15 08:37 UTC, rodneyosodo commented on users/api/endpoint_test.go
> +			err:    apiutil.ErrInvalidQueryParams,
Do we use the visibility field in `listClientsReq` if not remove it if we do add cases where visibility is invalid

2024-01-15 08:37 UTC, rodneyosodo commented on users/api/endpoint_test.go
> +			desc:        "update thing with valid token",
```suggestion
			desc:        "update user with valid token",
```

Same as other cases

2024-01-15 08:37 UTC, rodneyosodo commented on users/api/endpoint_test.go
> +		},
Add a case where id is empty

2024-01-15 08:54 UTC, 1998-felix commented on users/api/endpoint_test.go
> +	}{
When the ID is empty, it will call a different endpoint

2024-01-15 09:12 UTC, 1998-felix commented on users/api/endpoint_test.go
> +		},
When the ID is empty, it will call a different endpoint

2024-01-15 13:04 UTC, rodneyosodo requested changes

2024-01-15 13:04 UTC, rodneyosodo commented on users/postgres/clients_test.go
> +			desc: "retrieve by owner id with invalid owner id",
```suggestion
			desc: "retrieve with invalid owner id",
```

2024-01-15 13:04 UTC, rodneyosodo commented on users/postgres/clients_test.go
> +		{
Add a case where metadata is invalid

2024-01-15 13:04 UTC, rodneyosodo commented on users/postgres/clients_test.go
> +	}{
Add a case for role and identity

2024-01-15 13:04 UTC, rodneyosodo commented on users/api/requests_test.go
> +			desc: "invalid visibility",
We don't use visibility please remove it from the code and also API documentation and SDK

2024-01-16 09:22 UTC, rodneyosodo requested changes

2024-01-16 09:22 UTC, rodneyosodo commented on users/api/clients.go
>  	if oid != "" {
We don't need this and also sharedID

2024-01-17 08:55 UTC, rodneyosodo requested changes

2024-01-17 08:55 UTC, rodneyosodo commented on api/openapi/users.yml
> -
Also remove `UserVisibility`

2024-01-17 08:55 UTC, rodneyosodo commented on users/api/clients.go
>  	if oid != "" {
This has not be resolved. This is redundant

Try something like
```go
func decodeListClients(_ context.Context, r *http.Request) (interface{}, error) {
	s, err := apiutil.ReadStringQuery(r, api.StatusKey, api.DefClientStatus)
	if err != nil {
		return nil, errors.Wrap(apiutil.ErrValidation, err)
	}
	o, err := apiutil.ReadNumQuery[uint64](r, api.OffsetKey, api.DefOffset)
	if err != nil {
		return nil, errors.Wrap(apiutil.ErrValidation, err)
	}
	l, err := apiutil.ReadNumQuery[uint64](r, api.LimitKey, api.DefLimit)
	if err != nil {
		return nil, errors.Wrap(apiutil.ErrValidation, err)
	}
	m, err := apiutil.ReadMetadataQuery(r, api.MetadataKey, nil)
	if err != nil {
		return nil, errors.Wrap(apiutil.ErrValidation, err)
	}
	n, err := apiutil.ReadStringQuery(r, api.NameKey, "")
	if err != nil {
		return nil, errors.Wrap(apiutil.ErrValidation, err)
	}
	i, err := apiutil.ReadStringQuery(r, api.IdentityKey, "")
	if err != nil {
		return nil, errors.Wrap(apiutil.ErrValidation, err)
	}
	t, err := apiutil.ReadStringQuery(r, api.TagKey, "")
	if err != nil {
		return nil, errors.Wrap(apiutil.ErrValidation, err)
	}
	oid, err := apiutil.ReadStringQuery(r, api.OwnerKey, "")
	if err != nil {
		return nil, err
	}
	order, err := apiutil.ReadStringQuery(r, api.OrderKey, api.DefOrder)
	if err != nil {
		return nil, errors.Wrap(apiutil.ErrValidation, err)
	}
	dir, err := apiutil.ReadStringQuery(r, api.DirKey, api.DefDir)
	if err != nil {
		return nil, errors.Wrap(apiutil.ErrValidation, err)
	}
	st, err := mgclients.ToStatus(s)
	if err != nil {
		return nil, errors.Wrap(apiutil.ErrValidation, err)
	}
	req := listClientsReq{
		token:    apiutil.ExtractBearerToken(r),
		status:   st,
		offset:   o,
		limit:    l,
		metadata: m,
		name:     n,
		identity: i,
		tag:      t,
		owner:    oid,
		order:    order,
		dir:      dir,
	}

	return req, nil
}

```

2024-01-17 09:28 UTC, rodneyosodo requested changes

2024-01-17 09:28 UTC, rodneyosodo commented on users/postgres/clients_test.go
> +			Status:   mgclients.EnabledStatus,
Create some users who are disabled

2024-01-17 11:36 UTC, rodneyosodo commented on users/postgres/clients_test.go
> -			desc: "retrieve with enabled status",
Return this case `"retrieve with enabled status",`

2024-01-17 13:53 UTC, rodneyosodo approved these changes

2024-01-18 15:47 UTC, dborovcanin requested changes

2024-01-18 15:47 UTC, dborovcanin commented on users/postgres/clients_test.go
> +		page     mgclients.Page
Rename to `pageMeta`.

2024-01-18 15:47 UTC, dborovcanin commented on users/postgres/clients_test.go
> +		response mgclients.ClientsPage
Rename to `page`.

2024-01-18 15:47 UTC, dborovcanin commented on users/postgres/clients_test.go
> +					Total:  196,
Why not 200?

2024-01-18 16:04 UTC, 1998-felix commented on users/postgres/clients_test.go
> +					Total:  196,
When page is empty the status defaults to enabled clients and there are 4 disabled clients so the return is 196

2024-01-18 16:08 UTC, dborovcanin commented on users/postgres/clients_test.go
> +					Total:  196,
Please add a short comment on L463 explaining that.

2024-01-18 16:10 UTC, dborovcanin approved these changes

2024-01-18 16:14 UTC, merged