NOISSUE - Improve tests in things service
absmach/magistrala-old pull request #200
Opened 2023-12-22 11:05 UTC by 1998-felix

# What type of PR is this?
This is a feature as it increases the test coverage of the things service.

## What does this do?
Increase test coverage in users service and improves existing tests to match other packages.

## Which issue(s) does this PR fix/relate to?
None.

## Have you included tests for your changes?
No, since it is the test files.

## Did you document any new/modified feature?
No, 

### Notes

2024-01-03 08:41 UTC, rodneyosodo requested changes

2024-01-03 08:41 UTC, rodneyosodo commented on things/cache/things_test.go
> +	}{
Add unsuccessful scenarios

2024-01-03 08:41 UTC, rodneyosodo commented on things/cache/things_test.go
> +		{
Add a case where thingID returned is empty

2024-01-03 08:41 UTC, rodneyosodo commented on things/cache/things_test.go
> +	}{
Add unsuccessful scenarios

2024-01-03 08:41 UTC, rodneyosodo commented on things/service_test.go
> +	adminEmail   = "admin@example.com"
There are some scenarios missing tests try and run this locally and open `cover.html` in the browser to see cases that are missing
```bash
cd things && go test -tags test -v --race -covermode=atomic -coverprofile=cover.out ./... && go tool cover -html cover.out -o cover.html
```

This applies to `things/api/grpc/endpoint_test.go` and `things/api/http/endpoint_test.go`

2024-01-03 08:41 UTC, rodneyosodo commented on things/api/grpc/endpoint_test.go
> +const (
inline

2024-01-04 12:07 UTC, 1998-felix commented on things/service_test.go
> +	adminEmail   = "admin@example.com"
I have improved coverage for this, the only endpoints that are not covered are those for groups which are covered in internal

2024-01-04 12:42 UTC, rodneyosodo commented on things/service_test.go
> +	adminEmail   = "admin@example.com"
Add the following cases
- Authorize with nil error and authorised is false
- `CreateThings` with invalid token i.e identify to fail
- `CreateThings` with failed to authorize
- `CreateThings` with failed to add policies
-  `ViewClient` with repository error
- `ViewClientPerms` with repository error
- `UpdateClient` with failed to authorize
- `UpdateClientTags` with failed to authorize
- `UpdateClientSecret` with failed to authorize
- `changeClientStatus` with failed to authorize 
- `changeClientStatus` with failed to `RetrieveByID`
- `changeClientStatus` with `mgclients.ErrStatusAlreadyAssigned`
- `changeClientStatus` with failed to `ChangeStatus`
- `Share` with failed to add policies
- `Unshare` with failed to delete policies

Have a look at https://github.com/absmach/magistrala/pull/241 testing `ListClients`

2024-01-04 12:44 UTC, rodneyosodo commented on things/api/grpc/endpoint_test.go
> +	}{
Add cases where we have `InvalidArgument`, `PermissionDenied` and `Internal` as returned response codes

2024-01-04 12:46 UTC, rodneyosodo commented on things/api/http/endpoints_test.go
> +	}{
Add a case where `CreateThings` fails

2024-01-04 12:48 UTC, rodneyosodo commented on things/api/http/endpoints_test.go
> +	}{
Add more cases for example
- where request validation fails

Have a look at this https://github.com/absmach/magistrala/blob/b3e206321c9daded715eca23be5b6fd84d39c6f2/invitations/api/endpoint_test.go#L136

2024-01-04 12:50 UTC, rodneyosodo commented on things/api/http/endpoints_test.go
> +
Also test the following endpoints
- listMembersEndpoint
- assignUsersEndpoint
- unassignUsersEndpoint
- assignUserGroupsEndpoint
- unassignUserGroupsEndpoint
- connectChannelThingEndpoint
- disconnectChannelThingEndpoint
- connectEndpoint
- disconnectEndpoint

2024-01-04 12:52 UTC, rodneyosodo commented on things/cache/things_test.go
> +		{
save two keys one with empty thingID and the other one with a valid ID

2024-01-04 14:07 UTC, arvindh123 commented on things/service_test.go
> +func TestShare(t *testing.T) {
Please add test case for authorization

2024-01-08 07:03 UTC, 1998-felix commented on things/api/http/endpoints_test.go
> +
These endpoints will be implemented using service mocks for groups created in #243

2024-01-08 13:21 UTC, rodneyosodo commented on things/service_test.go
> +	adminEmail   = "admin@example.com"
- [ ] CreateThings with failed to add policies
- [ ] ListClients when `reqUserID` is empty has not been fully exhausted

2024-01-08 13:28 UTC, rodneyosodo requested changes

2024-01-08 13:28 UTC, rodneyosodo commented on things/api/grpc/endpoint_test.go
> +		_, err := client.Authorize(context.Background(), &magistrala.AuthorizeReq{})
Also check response

2024-01-08 13:28 UTC, rodneyosodo commented on things/api/http/endpoints_test.go
> +		},
Add cases for invalid query paramters that is status, metadata, name, owner, tag, permission and listperms have a look at https://github.com/absmach/magistrala/blob/main/invitations/api/endpoint_test.go#L249C1-L256C5

2024-01-08 13:28 UTC, rodneyosodo commented on things/api/http/endpoints_test.go
> +			contentType: contentType,
Add cases where the content type is invalid. This applies to all update operations

2024-01-09 13:02 UTC, arvindh123 commented on things/api/http/endpoints_test.go
> +
Could please include test for 
- assignUsersEndpoint
- unassignUsersEndpoint
- assignUserGroupsEndpoint
- unassignUserGroupsEndpoint
- connectChannelThingEndpoint
- disconnectChannelThingEndpoint
- connectEndpoint
- disconnectEndpoint

2024-01-09 14:14 UTC, 1998-felix commented on things/api/http/endpoints_test.go
> +
These endpoints in question relate to the groups service and I will add them using the svc mock generated in #241 once that is merged.

2024-01-10 08:29 UTC, rodneyosodo requested changes

2024-01-10 08:29 UTC, rodneyosodo commented on things/api/grpc/endpoint_test.go
> +		res, err := client.Authorize(context.Background(), &magistrala.AuthorizeReq{})
```suggestion
		res, err := client.Authorize(context.Background(), &tc.authorizeReq{})
```

2024-01-10 08:29 UTC, rodneyosodo commented on things/api/grpc/endpoint_test.go
> +		repocall := svc.On("Authorize", mock.Anything, &magistrala.AuthorizeReq{}).Return(tc.thingID, tc.err)
```suggestion
		repocall := svc.On("Authorize", mock.Anything, &tc.authorizeReq{}).Return(tc.thingID, tc.err)
```

2024-01-10 08:29 UTC, rodneyosodo commented on things/api/http/endpoints_test.go
> +			status:      http.StatusInternalServerError,
This should not be an InternalServerError - change `api.EncodeError` accordingly

2024-01-10 08:29 UTC, rodneyosodo commented on things/api/http/endpoints_test.go
> +			status:      http.StatusInternalServerError,
Same

2024-01-10 08:29 UTC, rodneyosodo commented on things/api/http/endpoints_test.go
> +			status:      http.StatusInternalServerError,
Make sure we don't return InternalServerError for all cases. Have a look at https://github.com/rodneyosodo/magistrala-dev/blob/6dc25210aa0fe56e7a1d29f4a07a790726b35a9a/internal/api/common.go#L100

2024-01-10 08:29 UTC, rodneyosodo commented on things/api/http/endpoints_test.go
> +		repoCall := svc.On("EnableClient", mock.Anything, mock.Anything, mock.Anything).Return(tc.response, tc.err)
Reduce the use of `mock.Anything`. This applies to all cases. try as much as possible to mock with correct values

2024-01-10 08:29 UTC, rodneyosodo commented on things/api/http/endpoints_test.go
> +	}{
Add a case where you list with all parameters

2024-01-10 08:29 UTC, rodneyosodo commented on things/api/http/requests_test.go
> +	validID := testsutil.GenerateUUID(t)
Make it a global variable

2024-01-10 08:29 UTC, rodneyosodo commented on things/cache/things_test.go
> +	tscache := cache.NewCache(redisClient, 10*time.Minute)
Change to 1 Minute

2024-01-10 08:29 UTC, rodneyosodo commented on things/cache/things_test.go
> +		key  string
We should use Key only not key with id

2024-01-10 08:29 UTC, rodneyosodo commented on things/cache/things_test.go
> +			desc: "Remove thing with empty ID from cache",
This should not return nil

2024-01-10 08:29 UTC, rodneyosodo commented on things/cache/things_test.go
> +
save with empty key but valid value

2024-01-11 08:10 UTC, rodneyosodo commented on things/api/http/endpoints_test.go
> +			status:      http.StatusInternalServerError,
This is unresolved

2024-01-11 12:37 UTC, arvindh123 commented on things/api/grpc/endpoint_test.go
> +			code: codes.Internal,
@1998-felix, 
This comment seems to be not addressed, 
Could you please check return error by the service for this request ?

2024-01-11 12:51 UTC, 1998-felix commented on things/api/grpc/endpoint_test.go
> +			code: codes.Internal,
Done.

2024-01-11 13:01 UTC, arvindh123 commented on things/service_test.go
> +			err:               repoerr.ErrCreateEntity,
Things can be created without identity

2024-01-11 13:57 UTC, arvindh123 commented on things/api/grpc/endpoint_test.go
> +			desc: "authorize successfully",
@1998-felix
Please add permission in Authorization request 
Something like this test case should be 
```json
{
"subject": "a1ca33c0-367e-402b-a239-ff1255fdc440111111",
"permission": "publish",
"object": "975a0164-968b-4975-b551-b87e51750749",
"object_type": "group"
}
```

2024-01-11 14:16 UTC, arvindh123 commented on things/api/grpc/endpoint_test.go
> +				Subject:     thingID,
@1998-felix
Please add test for following case
- invalid channelID
- invalid permission
- empty channelID,
- empty permission

2024-01-11 14:17 UTC, arvindh123 commented on things/api/grpc/endpoint_test.go
> +				SubjectType: auth.ThingType,
Convert publish string into constant,

2024-01-11 15:23 UTC, arvindh123 commented on things/api/grpc/endpoint_test.go
> +		repocall := svc.On("Authorize", mock.Anything, tc.authorizeReq).Return(tc.thingID, tc.err)
rename `repocall` to `svcCall`

2024-01-11 22:40 UTC, dborovcanin requested changes

2024-01-11 22:40 UTC, dborovcanin commented on things/service_test.go
> +		case "admin":
We have cases inside `for _, tc := range cases`. This implies we should probably only have two `for _, tc := range cases` (simply two case scenarios, maybe even two test functions are a good fit here) - one for admin, and other for non-admin.

2024-01-11 22:40 UTC, dborovcanin commented on things/service_test.go
> +		listPermissionsErr      error
Do we really need all these errors?

2024-01-12 07:52 UTC, 1998-felix commented on things/service_test.go
> +		case "admin":
I have separated them into two cases.

2024-01-12 07:54 UTC, 1998-felix commented on things/service_test.go
> +		listPermissionsErr      error
I use them to mock the response of each repo call.

2024-01-12 08:54 UTC, rodneyosodo requested changes

2024-01-12 08:54 UTC, rodneyosodo commented on things/postgres/clients_test.go
> +			err:  nil,
Change implementation to something like so that it returns a not found error

```go
result, err := repo.db.ExecContext(ctx, q, userID)
if err != nil {
	return postgres.HandleError(repoerr.ErrRemoveEntity, err)
}
if rows, _ := result.RowsAffected(); rows == 0 {
	return repoerr.ErrNotFound
}

return nil
```

2024-01-12 08:54 UTC, rodneyosodo commented on things/cache/things_test.go
> +			err:  nil,
Removing non-existing thing should return not found error. It is possible to implement that?

2024-01-12 08:54 UTC, rodneyosodo commented on things/cache/things_test.go
> +			err:  nil,
This should return an error. We can check that key is always not empty before retrieving from redis

2024-01-12 08:54 UTC, rodneyosodo commented on things/cache/things_test.go
> +			desc: "Save thing with empty key",
Add pre check so that this returns and error something like
```go
func (tc *thingCache) Save(ctx context.Context, thingKey, thingID string) error {
	if thingKey == "" || thingID == "" {
		return errors.New("thing key or thing id is empty")
	}

```

2024-01-12 08:54 UTC, rodneyosodo commented on things/api/grpc/endpoint_test.go
> +			res: &magistrala.AuthorizeRes{Authorized: false, Id: ""},
The string will default to empty and the boolean will default to false. This applies to other cases

```suggestion
			res: &magistrala.AuthorizeRes{},
```

2024-01-12 13:57 UTC, rodneyosodo requested changes

2024-01-12 13:57 UTC, rodneyosodo commented on things/cache/things_test.go
> +			desc: "Get thing ID from cache for empty ID",
We don't need this case

2024-01-12 13:57 UTC, rodneyosodo commented on things/cache/things_test.go
> +			key:  "",
Key should not be empty

2024-01-12 14:21 UTC, rodneyosodo approved these changes

2024-01-12 15:32 UTC, rodneyosodo approved these changes

2024-01-18 14:39 UTC, merged