MG220 - List all status domains by default
absmach/magistrala-old pull request #248
Opened 2024-01-02 17:12 UTC by arvindh123

# What type of PR is this?
This is a refactor because it changes the following functionality: 
- List all status domains by default 

## What does this do?
List all status domains by default 

## Which issue(s) does this PR fix/relate to?

- Resolves # https://github.com/absmach/magistrala/issues/220

## Have you included tests for your changes?

Yes, Tested manually endpoints

## Did you document any new/modified feature?

No, Not planned in this PR

2024-01-03 13:23 UTC, dborovcanin commented on auth/postgres/domains.go
> +	if pm.Status < auth.AllStatus {
Using `less than` in the context of enumeration is a little dangerous. Why do we change this?

2024-01-03 13:32 UTC, arvindh123 commented on auth/postgres/domains.go
> +	if pm.Status < auth.AllStatus {
If the `status` is less than enabled status (0), then there will no result 
` WHERE status = -1 `

Previously we had  `pm.status != auth.AllStatus` , In this case ,  if status greater than `AllStatus` (3) , then SQL will be like ` WHERE status = 5 `, this will not return any result 

But now if `pm.Status` is greater than `auth.AllStatus`,  then SQL will be like ` WHERE status = 3`, which will return result of all status

2024-01-05 09:28 UTC, arvindh123 commented on auth/postgres/domains.go
> +	if pm.Status < auth.AllStatus {
@dborovcanin 
Changed back to original

2024-01-05 09:56 UTC, rodneyosodo requested changes

2024-01-05 12:13 UTC, arvindh123 commented on auth/api/http/domains/decode.go
> +	s, err := apiutil.ReadStringQuery(r, api.StatusKey, auth.All)
Is there any specific reason for showing only enabled domains ? 
By default showing all domain will be useful for SuperAdmin and Domain Admin to login into disabled or freezed domain

2024-01-05 12:14 UTC, arvindh123 commented on auth/postgres/domains.go
> +	if pm.Status < auth.AllStatus {
@dborovcanin  `less than` will be useful in future when we have delete state which is greater than all status

2024-01-05 13:17 UTC, ianmuchyri commented on auth/api/http/domains/decode.go
> +	s, err := apiutil.ReadStringQuery(r, api.StatusKey, auth.All)
By default, a user (whether admin or not) should see the active entities based on how our UI is currently implemented. So by default, they should first see the active domains. Based on this UI pr https://github.com/absmach/magistrala-ui/pull/67, they should then be able to filter out and see either `all` , `enabled` or, `disabled` domains

as shown below: 
![image](https://github.com/absmach/magistrala/assets/100555904/7f0890c1-bbdd-421c-85e0-d865f386b2e5)

2024-01-10 10:13 UTC, dborovcanin approved these changes

2024-01-10 11:02 UTC, merged