MG-234 - Improve Logging
absmach/magistrala-old pull request #255
Opened 2024-01-04 06:41 UTC by Musilah

# What type of PR is this?
This is an optimisation as it improves logging.

## What does this do?
- Improves the searchability and filtering of logs
- Change the logger to slog from native package
- Add attributes of a unified naming style

## Which issue(s) does this PR fix/relate to?

- Resolves #234 

## Have you included tests for your changes?
No.

## Did you document any new/modified feature?
No.

### Notes

2024-01-04 08:04 UTC, dborovcanin requested changes
Let's first try to replace GoKit logger in our implementation with `slog` package described in the issue. We will take care of logging middleware after that.

2024-01-09 23:56 UTC, arvindh123 commented on users/api/logging.go
> +		}
Could you please explain here why there is need for var `fields`?

2024-01-10 00:29 UTC, Musilah commented on users/api/logging.go
> +		}
I wanted to allow filtering of log messages based on the fields map.

2024-01-10 01:00 UTC, arvindh123 commented on users/api/logging.go
>  	}(time.Now())
Something like below give output as JSON, which can be used for filtering
```suggestion
		fields := map[string]interface{}{
			"method":   "register_client",
			"id":       c.ID,
			"token":    token,
			"duration": time.Since(begin),
            "error" : "no errors / without errors"
		}
		if err != nil {
			fields["error"] = err.Error()
		}
		lm.logger.Info(ctx, fields)
	}(time.Now())
```
But At Present , it retruns as plain sentence text, How we will apply filtering on the plain text?

2024-01-10 08:49 UTC, rodneyosodo requested changes

2024-01-10 08:49 UTC, rodneyosodo commented on cmd/auth/main.go
> +	var chClientLogger mflog.Logger
No need for this. It can be done by. This applies to other occurrences 

```go
chClientLogger, err := mflog.New(os.Stdout, cfg.LogLevel)
if err != nil {
	logger.Error(ctx, fmt.Sprintf("failed to create logger: %s", err.Error()))
}
```

2024-01-10 08:49 UTC, rodneyosodo commented on cmd/bootstrap/main.go
> +	var logger mglog.Logger
No need for this

2024-01-10 08:49 UTC, rodneyosodo commented on cmd/http/main.go
> +	pcfg := config{}
Refactor the function to something like the pass the `chClientLogger` as the logger

```go
func proxyHTTP(ctx context.Context, cfg server.Config, logger mflog.Logger, sessionHandler session.Handler) error {
	address := fmt.Sprintf("%s:%s", "", cfg.Port)
	target := fmt.Sprintf("%s:%s", targetHTTPHost, targetHTTPPort)
	mp, err := mproxy.NewProxy(address, target, sessionHandler, logger)
	if err != nil {
		return err
	}
	http.HandleFunc("/", mp.Handler)

	errCh := make(chan error)
	switch {
	case cfg.CertFile != "" || cfg.KeyFile != "":
		go func() {
			errCh <- mp.ListenTLS(cfg.CertFile, cfg.KeyFile)
		}()
		logger.Info(fmt.Sprintf("%s service https server listening at %s:%s with TLS cert %s and key %s", svcName, cfg.Host, cfg.Port, cfg.CertFile, cfg.KeyFile))
	default:
		go func() {
			errCh <- mp.Listen()
		}()
		logger.Info(fmt.Sprintf("%s service http server listening at %s:%s without TLS", svcName, cfg.Host, cfg.Port))
	}

	select {
	case <-ctx.Done():
		logger.Info(fmt.Sprintf("proxy HTTP shutdown at %s", target))
		return nil
	case err := <-errCh:
		return err
	}
}
```

2024-01-10 08:49 UTC, rodneyosodo commented on cmd/mqtt/main.go
> +	var mpLogger mplog.Logger
No need for this

2024-01-10 08:49 UTC, rodneyosodo commented on logger/slogger.go
> +	"golang.org/x/exp/slog"
```suggestion
	"log/slog"
```

2024-01-10 08:49 UTC, rodneyosodo commented on logger/slogger.go
> +	err := level.UnmarshalText(levelText)
`UnmarshalText` returns different int values to what slog expects. Have a look at https://pkg.go.dev/log/slog#Level

2024-01-10 11:40 UTC, arvindh123 commented on logger/slogger.go
> +		AddSource: true,
In logs, source field points the
Logger Interface function 
```json 
{"time":"2024-01-10T11:39:37.320422745Z","level":"ERROR","source":{"function":"github.com/absmach/magistrala/logger.(*logger).Error","file":"/home/arvindh/arvindh123/magistrala-old/logger/slogger.go","line":66},"msg":"failed to setup service: unexpected gRPC status: Unavailable (status code:Unavailable) : connection error: desc = \"transport: Error while dialing: dial tcp 134.17.94.1:8181: connect: connection refused\""}
```

2024-01-11 08:11 UTC, rodneyosodo commented on logger/slogger.go
> +	err := level.UnmarshalText(levelText)
This is unresolved

2024-01-11 08:16 UTC, rodneyosodo requested changes
Also tests are failing

2024-01-11 08:16 UTC, rodneyosodo commented on logger/level.go
> +func (lvl *Level) UnmarshalText(data []byte) error {
No need for this change

2024-01-11 08:16 UTC, rodneyosodo commented on logger/slogger.go
> +		Level: slog.LevelDebug,
This should be the level from the function parameter

2024-01-11 12:30 UTC, dborovcanin requested changes

2024-01-11 12:30 UTC, dborovcanin commented on cmd/auth/main.go
> +		logger.Error(ctx, fmt.Sprintf("failed to init logger: %s", err.Error()))
If error is not nil, chances are that `logger` var is (i.e. `mglog.New` returned an error), so this code will panic.

2024-01-11 12:30 UTC, dborovcanin commented on logger/slogger.go
> +	err := level.UnmarshalText(levelText)
@Musilah Please take care of this.

2024-01-11 12:30 UTC, dborovcanin commented on logger/slogger.go
> +	slogLevel  :=mapLevelToSlog(*level)
This file is not properly formatted. Which editor and setup are you using?

2024-01-11 12:30 UTC, dborovcanin commented on logger/slogger.go
> +	if Debug.isAllowed(l.level) {
There is no need for these checks, `slog` already does this for us.

2024-01-12 13:08 UTC, ianmuchyri requested changes

2024-01-12 13:08 UTC, ianmuchyri commented on auth/api/http/keys/endpoint_test.go
> +	mux := httpapi.MakeHandler(svc, slog.Logger{}, "")
why not use the `newMock()` for logger

2024-01-12 13:08 UTC, ianmuchyri commented on auth/spicedb/policies.go
> +func (pa *policyAgent) publishToStream(ctx context.Context, resp *v1.WatchResponse) {
no need for this context

2024-01-12 13:08 UTC, ianmuchyri commented on bootstrap/api/endpoint_test.go
> +	mux := bsapi.MakeHandler(svc, bootstrap.NewConfigReader(encKey), slog.Logger{}, instanceID)
use `newMock()`

2024-01-12 13:08 UTC, ianmuchyri commented on bootstrap/postgres/configs.go
> +func (cr configRepository) rollback(ctx context.Context, content string, tx *sqlx.Tx) {
no need for the context

2024-01-12 13:08 UTC, ianmuchyri commented on certs/postgres/certs.go
> +func (cr certsRepository) rollback(ctx context.Context, content string, tx *sqlx.Tx, err error) {
no need for `context`. Remove other context scenarios that you added that we no longer need

2024-01-12 13:12 UTC, ianmuchyri requested changes

2024-01-12 13:12 UTC, ianmuchyri commented on twins/api/http/endpoint_twins_test.go
> +	mux := httpapi.MakeHandler(svc, slog.Logger{}, instanceID)
use `NewMock()` check for other tests as well

2024-01-12 13:17 UTC, arvindh123 commented on ws/api/endpoints.go
> +func encodeError(ctx context.Context, w http.ResponseWriter, err error) {
`ctx` is not used
Do we need to `context.Context` here ?

2024-01-12 13:18 UTC, arvindh123 commented on ws/api/endpoints.go
> +func decodeRequest(ctx context.Context, r *http.Request) (connReq, error) {
`ctx` is not used
Do we need to `context.Context` here ?

2024-01-12 14:19 UTC, ianmuchyri requested changes

2024-01-12 14:19 UTC, ianmuchyri commented on cmd/auth/main.go
> +	mflog "github.com/mainflux/mainflux/logger"
instead of using the mainflux logger you could use the kitlogger you have
```suggestion
	mflog "github.com/absmach/magistrala/kitlogger"
```

2024-01-12 14:19 UTC, ianmuchyri commented on cmd/auth/main.go
> +	mflog "github.com/mainflux/mainflux/logger"
you can do this for the rest

2024-01-12 14:27 UTC, ianmuchyri requested changes

2024-01-12 14:27 UTC, ianmuchyri commented on pkg/messaging/mqtt/pubsub.go
> +func (ps *pubsub) mqttHandler(ctx context.Context, h messaging.MessageHandler) mqtt.MessageHandler {
remove `context`

2024-01-12 14:27 UTC, ianmuchyri commented on pkg/messaging/mqtt/pubsub_test.go
> +func (h handler) Handle(ctx context.Context, msg *messaging.Message) error {
remove `context`

2024-01-12 14:27 UTC, ianmuchyri commented on pkg/messaging/mqtt/pubsub_test.go
> +func (h handler) Handle(ctx context.Context, msg *messaging.Message) error {
check the other places that need removing as well

2024-01-12 14:27 UTC, ianmuchyri commented on ws/api/endpoint_test.go
> +	mplog "github.com/absmach/magistrala/kitlogger"
```suggestion
	 "github.com/absmach/magistrala/kitlogger"
```

2024-01-12 14:27 UTC, ianmuchyri commented on ws/api/endpoint_test.go
> +	mp, err := websockets.NewProxy("", turl, mplog.NewMock(), svc)
```suggestion
	mp, err := websockets.NewProxy("", turl, kitlogger.NewMock(), svc)
```

2024-01-12 14:27 UTC, ianmuchyri commented on pkg/sdk/go/message_test.go
> +	mplog "github.com/absmach/magistrala/kitlogger"
```suggestion
	"github.com/absmach/magistrala/kitlogger"
```

2024-01-12 14:27 UTC, ianmuchyri commented on pkg/sdk/go/message_test.go
> +	mp, err := mproxy.NewProxy("", target.URL, handler, mplog.NewMock())
```suggestion
	mp, err := mproxy.NewProxy("", target.URL, handler, kitlogger.NewMock())
```

2024-01-12 14:27 UTC, ianmuchyri commented on http/api/endpoint_test.go
> +	mplog "github.com/absmach/magistrala/kitlogger"
```suggestion
	"github.com/absmach/magistrala/kitlogger"
```

2024-01-12 14:27 UTC, ianmuchyri commented on http/api/endpoint_test.go
> +	mp, err := mproxy.NewProxy("", targetServer.URL, svc, mplog.NewMock())
```suggestion
	mp, err := mproxy.NewProxy("", targetServer.URL, svc, kitlogger.NewMock())
```

2024-01-12 14:27 UTC, ianmuchyri commented on coap/api/transport.go
> +type ContextResponseWriter struct {
no need for this

2024-01-12 14:27 UTC, ianmuchyri commented on cmd/auth/main.go
> +	chClientLogger, err := mflog.New(os.Stdout, cfg.LogLevel)
```suggestion
	chClientLogger, err := kitlogger.New(os.Stdout, cfg.LogLevel)
```

2024-01-12 14:31 UTC, ianmuchyri requested changes

2024-01-12 14:31 UTC, ianmuchyri commented on internal/apiutil/transport_test.go
> +			errorEncoder := apiutil.LoggingErrorEncoder(slog.Logger{}, encFunc)
use `NewMock()`, this is why test is failing

2024-01-12 14:37 UTC, rodneyosodo requested changes

2024-01-12 14:37 UTC, rodneyosodo commented on logger/level.go
> +func UnmarshalText(text string) (slog.Level, error) {
We don't need this

2024-01-15 09:12 UTC, rodneyosodo requested changes

2024-01-15 09:12 UTC, rodneyosodo commented on logger/logger.go
> +func New(w io.Writer, levelText string) (slog.Logger, error) {
Change this to something like, also make sure to return a pointer to the struct

```go
func New(w io.Writer, levelText string) (*slog.Logger, error) {
	var level slog.Level
	if err := level.UnmarshalText([]byte(levelText)); err != nil {
		return &slog.Logger{}, fmt.Errorf(`{"level":"error","message":"%s: %s","ts":"%s"}`, err, levelText, time.RFC3339Nano)
	}

	logHandler := slog.NewJSONHandler(w, &slog.HandlerOptions{
		Level: level,
	})

	return slog.New(logHandler), nil
}
```

2024-01-15 09:12 UTC, rodneyosodo commented on kitlogger/kitdodc.go
> +package kitlogger
There is no need for this package you can return it to the `logger` package and create another function called `NewSlog` which returns the slog logger. Then we will deprecate it in future

2024-01-15 13:11 UTC, rodneyosodo requested changes

2024-01-15 13:11 UTC, rodneyosodo commented on coap/api/logging.go
> +	logger slog.Logger
```suggestion
	logger *slog.Logger
```

This applies to all places

2024-01-15 13:11 UTC, rodneyosodo commented on coap/api/logging.go
> +func LoggingMiddleware(svc coap.Service, logger slog.Logger) coap.Service {
```suggestion
func LoggingMiddleware(svc coap.Service, logger *slog.Logger) coap.Service {
```
This applies to all places

2024-01-17 07:59 UTC, rodneyosodo requested changes

2024-01-17 07:59 UTC, rodneyosodo commented on auth/api/http/domains/transport.go
> +func MakeHandler(svc auth.Service, mux *chi.Mux, logger slog.Logger) *chi.Mux {
```suggestion
func MakeHandler(svc auth.Service, mux *chi.Mux, logger *slog.Logger) *chi.Mux {
```

Use pointers this applies in other cases too

2024-01-17 10:53 UTC, dborovcanin commented on auth/api/http/domains/transport.go
> +func MakeHandler(svc auth.Service, mux *chi.Mux, logger slog.Logger) *chi.Mux {
@Musilah Please address these.

2024-01-17 13:25 UTC, rodneyosodo requested changes

2024-01-17 13:25 UTC, rodneyosodo commented on bootstrap/postgres/configs.go
> +	log slog.Logger
Use pointer

2024-01-17 13:25 UTC, rodneyosodo commented on certs/postgres/certs.go
> +	log slog.Logger
Use pointer

2024-01-17 13:25 UTC, rodneyosodo commented on lora/mqtt/sub.go
> +	logger  slog.Logger
Same

2024-01-17 13:25 UTC, rodneyosodo commented on pkg/messaging/rabbitmq/setup_test.go
> +	logger, err = mglog.New(os.Stdout, "info")
```suggestion
	logger, err = mglog.New(os.Stdout, "debug")
```

2024-01-17 13:25 UTC, rodneyosodo commented on logger/doc.go
> +// Package logger contains kitLogger and slogger API definition, wrapper that
Revert to how it was before

2024-01-17 13:25 UTC, rodneyosodo commented on logger/logger.go
> +	if err != nil {
Inline

2024-01-17 13:25 UTC, rodneyosodo commented on logger/logger.go
> +func NewKitLog(out io.Writer, levelText string) (Logger, error) {
Change go docs too

2024-01-17 13:25 UTC, rodneyosodo commented on logger/mock.go
> +func NewKitMock() Logger {
Change go docs to align with the function

2024-01-17 13:25 UTC, rodneyosodo commented on logger/logger_test.go
> +			level:  "debug",
```suggestion
			level:  LevelDebug,
```

same as other cases

2024-01-17 13:25 UTC, rodneyosodo commented on logger/logger_test.go
> +const (
No need to export these constants

2024-01-17 14:57 UTC, Musilah commented on logger/logger_test.go
> +const (
These constants are needed for the levels as well as for this `if tc.level != LevelWarn && tc.level != LevelInfo && tc.level != LevelDebug `

2024-01-17 15:52 UTC, rodneyosodo commented on logger/logger_test.go
> +const (
They should not be exported since they are being used ing the `_test` package

2024-01-18 08:49 UTC, rodneyosodo requested changes

2024-01-18 08:49 UTC, rodneyosodo commented on logger/logger.go
> +// New returns wrapped logger.
```suggestion
// New returns wrapped slog logger.
```

2024-01-18 08:49 UTC, rodneyosodo commented on logger/mock.go
> +// NewMock returns wrapped logger mock.
```suggestion
// NewMock returns wrapped slog logger mock.
```

2024-01-18 08:49 UTC, rodneyosodo commented on cmd/ws/main.go
> +		chc := chclient.New(svcName, magistrala.Version, chClientLogger, cancel)
Update version of `callhome` client as it no longer uses magistrala logger but slog

2024-01-18 11:37 UTC, rodneyosodo requested changes

2024-01-18 11:37 UTC, rodneyosodo commented on cmd/ws/main.go
> +	cfg := config{}
We don't need this

2024-01-18 11:37 UTC, rodneyosodo commented on logger/logger_test.go
> +	"log/slog"
Refactor test to only test initialization

2024-01-18 11:37 UTC, rodneyosodo commented on cmd/opcua/main.go
> +func newRouteMapRepositoy(ctx context.Context, client *redis.Client, prefix string, logger *slog.Logger) opcua.RouteMapRepository {
context is unused

2024-01-18 13:08 UTC, rodneyosodo requested changes

2024-01-18 13:08 UTC, rodneyosodo commented on logger/logger_test.go
> +			level: slog.LevelError.String(),
Add case where level is invalid

2024-01-18 13:35 UTC, rodneyosodo approved these changes

2024-01-18 13:43 UTC, ianmuchyri approved these changes

2024-01-18 14:27 UTC, dborovcanin approved these changes

2024-01-18 14:28 UTC, merged