MG221 - Handling things gRPC error
absmach/magistrala-old pull request #257
Opened 2024-01-04 08:57 UTC by arvindh123

# What type of PR is this?

## What does this do?
Handling of things gRPC errors in both server and client 

## Which issue(s) does this PR fix/relate to?

- Related Issue #221 

## Have you included tests for your changes?

Test partially, Websocket and HTTP doesn

## Did you document any new/modified feature?

No, Not related 

### Notes

2024-01-08 08:12 UTC, rodneyosodo requested changes

2024-01-08 08:12 UTC, rodneyosodo commented on things/service.go
> +		return "", errors.Wrap(svcerr.ErrAuthorization, err)
Shouldn't this remain to NotFound ?

2024-01-08 12:01 UTC, arvindh123 commented on things/service.go
> +		return "", errors.Wrap(svcerr.ErrAuthorization, err)
From the point of Authorization, If the secret is not found then it is invalid secret.

2024-01-10 10:12 UTC, dborovcanin requested changes

2024-01-10 10:12 UTC, dborovcanin commented on things/api/grpc/client.go
> +			return nil
Is it likely that the OK code will happen with the nil error? I suspect this case should be either first or last. Also, order cases by the probability (according to your experience) from most frequent to least.

2024-01-10 12:37 UTC, arvindh123 commented on things/api/grpc/client.go
> +			return nil
If there is no error, we return nill error in MG codes
But gRPC have option to send not error in error status
So only just handled it.

Moved to last case

2024-01-10 15:51 UTC, dborovcanin approved these changes

2024-01-10 15:52 UTC, merged