NOISSUE - Limit Max Traces kept in-memory by Jaeger all-in-one
absmach/magistrala-old pull request #259
Opened 2024-01-04 14:33 UTC by charlie-jangala

# What type of PR is this?

This is a bug fix because it addresses a possible cause of OOM events in the default docker deployment configuration.

## What does this do?

It limits the number of traces kept in-memory by the Jaeger all-in-one container, which otherwise places no limit on the number of traces it stores. From the Jaeger documentation (https://www.jaegertracing.io/docs/1.52/deployment/#memory):

```
The in-memory storage is not intended for production workloads. It’s intended as a simple solution to get started quickly and data will be lost once the process is gone.

By default, there’s no limit in the amount of traces stored in memory but a limit can be established by passing an integer value via --memory.max-traces.
```

This PR introduces the mentioned `--memory.max-traces` flag to the `docker-compose.yml`, and sets a conservative default value of 5000.

## Which issue(s) does this PR fix/relate to?

- Related Issue #
- Resolves #

## Have you included tests for your changes?

No as no changes made to the Magistrala codebase itself. The change was tested by running Magistrala on my local machine with the updated `docker-compose.yml`.

## Did you document any new/modified feature?

No, because I'm not sure if it needs to be documented anywhere.

### Notes

2024-01-09 11:36 UTC, rodneyosodo requested changes

2024-01-09 11:36 UTC, rodneyosodo commented on docker/docker-compose.yml
> +    command: --memory.max-traces ${MG_JAEGER_MEMORY_MAX_TRACES}
I'd suggest changing from in-memory to local storage https://www.jaegertracing.io/docs/1.52/deployment/#badger---local-storage

2024-01-10 16:34 UTC, dborovcanin commented on docker/docker-compose.yml
> +    command: --memory.max-traces ${MG_JAEGER_MEMORY_MAX_TRACES}
@charlie-jangala Do you have any plans on changing this to use Badger storage backed? If not, we can close this one and @rodneyosodo will send an update in another PR. Limiting the number of traces makes sense, but the solution @rodneyosodo suggested is a little bit more flexible.

2024-01-18 17:17 UTC, charlie-jangala commented on docker/docker-compose.yml
> +    command: --memory.max-traces ${MG_JAEGER_MEMORY_MAX_TRACES}
Hi @dborovcanin and @rodneyosodo , thanks for the input. I agree that Badger would be a more production-calibre setup than limiting the max traces in-memory; but, I also think that the effort to add Badger would be better directed towards adding support for Cassandra, ElasticSearch or OpenSearch, given these are the backends which Jaeger endorses as legitimate production backend options. I also believe these would be more easily extensible to a Kubernetes deployment of Magistrala than Badger would be.

To that end, I'd propose merging this change if you are happy with it, and adding an issue (I'm happy to add it) to support Cass/ES/OS, and give users the choice between this and the in-memory setup. I can try pick that up when I have capacity, unless someone else wants to take it on first.

Let me know what you think.

2024-01-19 10:30 UTC, dborovcanin commented on docker/docker-compose.yml
> +    command: --memory.max-traces ${MG_JAEGER_MEMORY_MAX_TRACES}
I'm OK with this. Local storage seems to be a better fit from the resources perspective (so we do not store traces in RAM), but we can change that if there is a need; this will also do the job for development purposes. We will soon migrate Magistrala (old Mainflux) deployment scripts to this organization and we can open a ticket there. All the help for prod scripts is appreciated @charlie-jangala.

2024-01-19 10:31 UTC, dborovcanin approved these changes

2024-01-19 10:34 UTC, merged