Mg253 domains api spec
absmach/magistrala-old pull request #261
Opened 2024-01-04 15:58 UTC by arvindh123

# What type of PR is this?
This is a documentation update because it updates the following documentation: 
- Add Domains openAPI spec 

## What does this do?
- Add Domains openAPI spec 

## Which issue(s) does this PR fix/relate to?

- Related Issue #
- Resolves #253 

## Have you included tests for your changes?

No,  Not Applicable

## Did you document any new/modified feature?

No, Not Applicable
### Notes

2024-01-05 12:45 UTC, ianmuchyri requested changes

2024-01-05 12:45 UTC, ianmuchyri commented on api/openapi/auth.yml
> +          description: Failed due to using an existing identity.
the unique variable being used at the moment is `alias`?

2024-01-05 12:45 UTC, ianmuchyri commented on api/openapi/auth.yml
> +        Retrieves a specific domain that is identifier by the domain ID.
```suggestion
        Retrieves a specific domain that is identified by the domain ID.
```

2024-01-05 12:45 UTC, ianmuchyri commented on api/openapi/auth.yml
> +        Updates name and alias of the domain.
`metadata` and `tags` are also updated in this request

2024-01-05 12:45 UTC, ianmuchyri commented on api/openapi/auth.yml
> +        Enables a specific domain that is identifier by the domain ID.
```suggestion
        Enables a specific domain that is identified by the domain ID.
```

2024-01-05 12:45 UTC, ianmuchyri commented on api/openapi/auth.yml
> +        Disable a specific domain that is identifier by the domain ID.
```suggestion
        Disable a specific domain that is identified by the domain ID.
```

2024-01-05 12:45 UTC, ianmuchyri commented on api/openapi/auth.yml
> +        Freeze a specific domain that is identifier by the domain ID.
```suggestion
        Freeze a specific domain that is identified by the domain ID.
```

2024-01-05 12:45 UTC, ianmuchyri commented on api/openapi/auth.yml
> +        Freeze a specific domain that is identifier by the domain ID.
do the same for the rest

2024-01-05 12:45 UTC, ianmuchyri commented on api/openapi/auth.yml
> +        "409":
does a get request result in an error `409`?

2024-01-05 12:45 UTC, ianmuchyri commented on api/openapi/auth.yml
> +          description: User ID of user created domain.
```suggestion
          description: User ID of the user who created the domain.
```

2024-01-05 12:45 UTC, ianmuchyri commented on api/openapi/auth.yml
> +          description: User ID of user last updated domain.
```suggestion
          description: User ID of the user who last updated the domain.
```

2024-01-05 12:45 UTC, ianmuchyri commented on api/openapi/auth.yml
> +          description: Time when the domain was last update.
```suggestion
          description: Time when the domain was last updated.
```

2024-01-05 12:45 UTC, ianmuchyri commented on api/openapi/auth.yml
> +      description: JSON-formated document describing the metadata and name of domain to be update
```suggestion
      description: JSON-formated document describing the name, alias, tags, and metadata of the domain to be updated
```

2024-01-05 12:45 UTC, ianmuchyri commented on api/openapi/auth.yml
> +      description: JSON-formated document describing the policy related to assigning users to a domain
```suggestion
      description: JSON-formated document describing the policy related to unassigning users to a domain
```

2024-01-05 12:47 UTC, arvindh123 commented on api/openapi/auth.yml
> +          description: Failed due to using an existing identity.
Yes

2024-01-05 12:47 UTC, arvindh123 commented on api/openapi/auth.yml
> +        Updates name and alias of the domain.
Yes , I will update the description

2024-01-05 13:01 UTC, ianmuchyri requested changes

2024-01-05 13:01 UTC, ianmuchyri commented on api/openapi/auth.yml
> +          description: Failed due to using an existing identity.
this then should be:

```suggestion
          description: Failed due to using an existing alias.
```

2024-01-05 13:03 UTC, ianmuchyri approved these changes

2024-01-08 08:17 UTC, rodneyosodo requested changes

2024-01-08 08:17 UTC, rodneyosodo commented on api/openapi/auth.yml
> +  /domains:
Also document 
- list_domains_by_user_id
- view_domain_permissions

2024-01-08 08:17 UTC, rodneyosodo commented on api/openapi/auth.yml
> +  /domains/{domainID}/users:
This endpoint is not implemented

2024-01-09 06:36 UTC, arvindh123 commented on api/openapi/auth.yml
> +  /domains:
/users/{userID}/domains - This endpoint belongs to users , but endpoint is present in Auth service

2024-01-09 06:37 UTC, arvindh123 commented on api/openapi/auth.yml
> +  /domains/{domainID}/users:
This endpoint was implemented in Users service

2024-01-09 09:07 UTC, arvindh123 commented on api/openapi/auth.yml
> +  /domains/{domainID}/users:
It was implemented in Users service ,

2024-01-09 09:18 UTC, rodneyosodo commented on api/openapi/auth.yml
> +  /domains/{domainID}/users:
Shouldn't it be documented in the users service?

2024-01-09 09:18 UTC, rodneyosodo commented on api/openapi/auth.yml
> +  /domains:
But isn't it under auth service?

2024-01-09 09:37 UTC, arvindh123 commented on api/openapi/auth.yml
> +  /domains:
In the OpenAPI specification, I suggest structuring API endpoints not based on service-specific endpoints but rather on entities. 
For example, within the `users.yml` file, all endpoints would start with `/users`. Operations related to specific users, such as retrieving user tags (`users/{userID}/tag`), would be included here. However, I propose including additional endpoints, like `/users/{userID}/things`, which pertain to the 'things' associated with a user, even if the 'things' functionality resides in a different service.

By including such endpoints in the `users.yml` API specification, users interacting with this document will find it easier to understand as they would expect `users.Yaml` to provide comprehensive user-related functionalities, even if certain functionalities are fulfilled by other services.

2024-01-09 09:50 UTC, rodneyosodo commented on api/openapi/auth.yml
> +  /domains:
Shouldn't it be documentation of a specific micro-service(server)?

2024-01-10 11:07 UTC, dborovcanin commented on api/openapi/auth.yml
> +  /domains:
I do not mind having endpoints from different services, but we generally keep services and entities logically correlated anyway. For the given example, maybe we should change the API for `Things`. I.e. this is filtering of things, so something like `/things?user=id` is more suitable anyways.

2024-01-10 13:35 UTC, arvindh123 commented on api/openapi/auth.yml
> +  /domains:
I agree with your idea https://github.com/absmach/magistrala-old/pull/261#discussion_r1447229367
I will check the possibilities in code and create a new issue

2024-01-10 15:45 UTC, dborovcanin approved these changes

2024-01-10 15:46 UTC, merged