NOISSUE- Improve tests in Auth service
absmach/magistrala-old pull request #262
Opened 2024-01-05 07:11 UTC by 1998-felix

# What type of PR is this?
This is a feature because it improves tests and test coverage in the auth service.

## What does this do?
Increase coverage of tests in auth.

None.

## Which issue(s) does this PR fix/relate to?
None.

## Have you included tests for your changes?
No since these are test files.

## Did you document any new/modified feature?
No

### Notes
None

2024-01-17 09:08 UTC, rodneyosodo requested changes
There are test cases missing. Run the following command to find out the missing cases
```go
cd auth && go test -tags test -v --race -covermode=atomic -coverprofile=cover.out ./... && go tool cover -html cover.out -o cover.html
```

2024-01-17 09:08 UTC, rodneyosodo commented on auth/mocks/authservice.go
> +type AuthService struct {
generate mocks rather than writing them

2024-01-17 09:08 UTC, rodneyosodo commented on auth/domains.go
> +//go:generate mockery --name Domains --output=./mocks --filename domains_service.go --quiet --note "© 2020 Abstract Machines Works"
These mocks have not been generated

2024-01-17 09:08 UTC, rodneyosodo commented on auth/api/http/domains/endpoint.go
> +			fmt.Println("enableDomainEndpoint err: ", err)
Remove this debug statement

2024-01-17 09:08 UTC, rodneyosodo commented on auth/api/grpc/endpoint_test.go
> +		repoCall := svc.On("Issue", mock.Anything, mock.Anything, mock.Anything, mock.Anything).Return(auth.Token{}, tc.err)
Don't always return empty token

2024-01-17 09:08 UTC, rodneyosodo commented on auth/api/http/domains/endpoint_test.go
> +	loginDuration   = 30 * time.Minute
Are we using these variables?

2024-01-19 15:23 UTC, rodneyosodo requested changes

2024-01-19 17:21 UTC, 1998-felix commented on auth/service.go
> +
This case is never reached as tokenizer never returns the specified error. This section requires a refactor

2024-01-23 08:53 UTC, rodneyosodo requested changes

2024-01-23 08:53 UTC, rodneyosodo commented on auth/api/grpc/endpoint_test.go
> +	}
On testing do we reach this condition
```go
if len(req.GetFilterPermissions()) > 0 {
	fp = req.GetFilterPermissions()
}
```

2024-01-23 08:53 UTC, rodneyosodo commented on auth/api/grpc/endpoint_test.go
> +	conn, _ := grpc.Dial(authAddr, grpc.WithTransportCredentials(insecure.NewCredentials()))
Don't ignore this error handle it. Same as other cases

2024-01-23 08:53 UTC, rodneyosodo commented on auth/service.go
> +
Refactor it then

2024-01-23 08:53 UTC, rodneyosodo commented on auth/api/grpc/endpoint_test.go
> +	validID         = "d4ebb847-5d0e-4e46-bdd9-b6aceaaa3a22"
Use `testsutil.GenerateUUID(&testing.T{})`

2024-01-23 08:53 UTC, rodneyosodo commented on auth/api/grpc/endpoint_test.go
>  func startGRPCServer(svc auth.Service, port int) {
Don't panic handle that error with require Nil

2024-01-23 08:53 UTC, rodneyosodo commented on auth/api/grpc/endpoint_test.go
>  )
Declare `authAddr` as a global variable

2024-01-23 08:53 UTC, rodneyosodo commented on auth/api/grpc/endpoint_test.go
> +		email         string
Are we using email and code?

2024-01-23 08:53 UTC, rodneyosodo commented on auth/api/grpc/endpoint_test.go
> +		code          codes.Code
Also use domain ID

2024-01-23 08:53 UTC, rodneyosodo commented on auth/api/grpc/endpoint_test.go
> +		code          codes.Code
Are we using code ?

2024-01-23 08:53 UTC, rodneyosodo commented on auth/api/grpc/endpoint_test.go
> +		err           error
Add domainID

2024-01-23 08:53 UTC, rodneyosodo commented on auth/api/grpc/endpoint_test.go
> +		ar, err := client.Authorize(context.Background(), &magistrala.AuthorizeReq{Subject: tc.subject, SubjectType: tc.subjecttype, Object: tc.object, ObjectType: tc.objecttype, Relation: tc.relation, Per
Combine them so that you can use 
```suggestion
		ar, err := client.Authorize(context.Background(), tc.authReq)
```

2024-01-23 08:53 UTC, rodneyosodo commented on auth/api/grpc/endpoint_test.go
> +		ar, err := client.Authorize(context.Background(), &magistrala.AuthorizeReq{Subject: tc.subject, SubjectType: tc.subjecttype, Object: tc.object, ObjectType: tc.objecttype, Relation: tc.relation, Per
Same as other cases

2024-01-23 08:53 UTC, rodneyosodo commented on auth/domains_test.go
> +
Not all cases have been covered

2024-01-23 11:48 UTC, 1998-felix commented on auth/api/grpc/endpoint_test.go
> +	}
We do not.

2024-01-24 10:35 UTC, dborovcanin requested changes

2024-01-24 10:35 UTC, dborovcanin commented on auth/postgres/domains.go
> +	q := "DELETE FROM domains WHERE id = $1 ;"
Remove trailing space before semicolon: `q := "DELETE FROM domains WHERE id = $1;"`.

2024-01-24 10:35 UTC, dborovcanin commented on auth/postgres/domains.go
> +	result, err := repo.db.ExecContext(ctx, q, id)
Shorten to `res, err`.

2024-01-24 11:43 UTC, dborovcanin requested changes

2024-01-24 11:43 UTC, dborovcanin commented on auth/api/grpc/requests.go
> +	// To implement validation for policies.
Remove TODO comments and open a ticket.

2024-01-24 11:51 UTC, 1998-felix commented on auth/api/grpc/requests.go
> +	// To implement validation for policies.
I have removed the comment, the issue :https://github.com/absmach/magistrala/issues/1979

2024-01-24 15:02 UTC, dborovcanin requested changes

2024-01-24 15:14 UTC, 1998-felix commented on auth/mocks/authservice.go
> +type AuthService struct {
Yes it is. It is for the grpc calls from other services.

2024-01-24 16:06 UTC, dborovcanin commented on auth/mocks/authservice.go
> +type AuthService struct {
Rename this file `auth_client.go` and rename the struct to `AuthClient`.

2024-01-24 16:38 UTC, dborovcanin approved these changes

2024-01-25 13:02 UTC, dborovcanin approved these changes

2024-01-25 13:03 UTC, merged