MG104: Rename/Replace filed owner to domain
absmach/magistrala-old pull request #268
Opened 2024-01-08 11:02 UTC by arvindh123

# What type of PR is this?
This is a refactor because it changes the following functionality: 
-  Rename/Replace filed owner to domain in all services

## What does this do?

## Which issue(s) does this PR fix/relate to?

- Resolves #104 

## Have you included tests for your changes?

Yes, WIP

## Did you document any new/modified feature?

Yes, WIP

2024-01-26 16:11 UTC, dborovcanin requested changes

2024-01-26 16:11 UTC, dborovcanin commented on api/openapi/things.yml
> +        Creates new channel. Domain identified by the provided access token will.
Fix.

2024-01-26 16:11 UTC, dborovcanin commented on things/api/http/endpoints_test.go
> -				Clients: []mgclients.Client{client},
These tests are still relevant, just replace the owner with the domain.

2024-01-26 17:19 UTC, arvindh123 commented on things/api/http/endpoints_test.go
> -				Clients: []mgclients.Client{client},
@dborovcanin Yesterday, I missed to push one commit
This is no more needed, It was removed
Things list with owner_id (domain_id) will not work

2024-01-26 17:20 UTC, arvindh123 commented on api/openapi/things.yml
> +        Creates new channel. Domain identified by the provided access token will.
@dborovcanin Fixed

2024-01-26 17:41 UTC, dborovcanin commented on api/openapi/things.yml
> +        Creates new channel. Domain identified by the provided access token will.
This is not fixed.

2024-01-27 21:45 UTC, dborovcanin approved these changes

2024-01-27 21:47 UTC, merged