MG-234 - Improve Logging Middleware
absmach/magistrala-old pull request #272
Opened 2024-01-15 06:19 UTC by Musilah

# What type of PR is this?
This is an optimisation for Logging.

## What does this do?
This improves Logging by updating the filtering and searchability through structured logs. 

## Which issue(s) does this PR fix/relate to?

- Related Issue #255 

## Have you included tests for your changes?
No.

## Did you document any new/modified feature?
No.

### Notes
N/A.

2024-01-15 09:59 UTC, rodneyosodo requested changes

2024-01-15 09:59 UTC, rodneyosodo commented on bootstrap/api/logging.go
> +			lm.logger.Warn(
This is an example log message
```json
{"time":"2024-01-15T09:55:05.684738353Z","level":"INFO","msg":"Method register_client completed without errors.","method":"register_client","client_id":"20538e47-25f8-41eb-b288-97d76003b3c9","token":"","duration":"59.803857ms"}
{"time":"2024-01-15T09:55:05.733256617Z","level":"INFO","msg":"Method issue_token of type  completed without errors.","method":"issue_token","identity":"Genovesi-Hollenbeck@email.com","domain_id":"","duration":"47.369737ms"}
```

I'd suggest something like to avoid repetition

```json
{"time":"2024-01-15T09:55:05.684738353Z","level":"INFO","method":"register_client","client_id":"20538e47-25f8-41eb-b288-97d76003b3c9","token":"","duration":"59.803857ms"}
{"time":"2024-01-15T09:55:05.733256617Z","level":"INFO","method":"issue_token","identity":"Genovesi-Hollenbeck@email.com","domain_id":"","duration":"47.369737ms"}
```

2024-01-17 14:20 UTC, rodneyosodo requested changes

2024-01-17 14:20 UTC, rodneyosodo commented on users/api/logging.go
> +			lm.logger.Warn("Register client failed to complete successfully", args...)
Error

2024-01-17 14:20 UTC, rodneyosodo commented on users/api/logging.go
> +			slog.Group("user", slog.String("client_name", c.Name), slog.String("client_ID", c.ID)),
```go
slog.Group("user", slog.String("name", c.Name), slog.String("id", c.ID)),
```

2024-01-17 14:20 UTC, rodneyosodo commented on users/api/logging.go
> +			slog.String("domain_ID", domainID),
use json compatible keys

```go
slog.String("domain_id", domainID),
```

2024-01-17 15:21 UTC, Musilah commented on users/api/logging.go
> +			lm.logger.Warn("Register client failed to complete successfully", args...)
should all the warn logs be error logs now?

2024-01-21 15:37 UTC, dborovcanin requested changes

2024-01-21 15:37 UTC, dborovcanin commented on users/api/logging.go
> +			lm.logger.Error("Register client failed to complete successfully", args...)
Let's use `warn`. The correct log level, however, can only be set properly by inspecting the error; we'll not do that in this PR.

2024-01-22 10:54 UTC, ianmuchyri requested changes

2024-01-22 10:54 UTC, ianmuchyri commented on auth/api/logging.go
> +			args = append(args, slog.String("error", err.Error()))
```suggestion
			args = append(args, slog.Any("error", err))
```

Do this for the rest. It returns a better error format

2024-01-22 11:10 UTC, rodneyosodo requested changes
I have reviewed logging in `ws`, `users`, `things`, `twins`, `readers`, `provision` and messaging use that information to change the other services

Also have a look at this case

```go
func (lm *loggingMiddleware) Cert(token, thingID, duration string) (cert, key string, err error) {
	defer func(begin time.Time) {
		args := []interface{}{
			slog.String("duration", time.Since(begin).String()),
			slog.String("thing_id", thingID),
			slog.String("duration", duration),
		}
		if err != nil {
			args = append(args, slog.String("error", err.Error()))
			lm.logger.Warn("Cert failed to complete successfully", args...)
			return
		}
		lm.logger.Info("Cert completed successfully", args...)
	}(time.Now())

	return lm.svc.Cert(token, thingID, duration)
}
```

This is found in provision. This logs is not informative or clear on what it does `Cert completed successfully` because the underlying function creates a certificate. Use go docs to infer what a function does and make the log statemes clear and concise as to what is happening

2024-01-22 11:10 UTC, rodneyosodo commented on things/api/logging.go
> +			lm.logger.Warn("View client failed to complete successfully", args...)
```suggestion
			lm.logger.Warn("View thing failed to complete successfully", args...)
```

Do this for all cases

2024-01-22 11:10 UTC, rodneyosodo commented on things/api/logging.go
> +				slog.String("key", key),
Don't log key

2024-01-22 11:10 UTC, rodneyosodo commented on things/api/logging.go
> +			slog.String("thing_key", req.Subject),
Use the getter functions to extract values from the struct

2024-01-22 11:10 UTC, rodneyosodo commented on readers/api/logging.go
> +			slog.String("channel_ID", chanID),
Use json format for logging key value pairs i.e use snake_case

2024-01-22 11:10 UTC, rodneyosodo commented on readers/api/logging.go
> +				slog.String("subtopic", rpm.Subtopic),
Subtopic and publisher might be empty add them if they aren't same to other values in `Page`

2024-01-22 11:10 UTC, rodneyosodo commented on provision/api/logging.go
> +			slog.String("external_key", externalKey),
remove this

2024-01-22 11:10 UTC, rodneyosodo commented on provision/api/logging.go
> +			slog.String("duration", duration),
you have 2 duration keys

2024-01-22 11:10 UTC, rodneyosodo commented on pkg/messaging/handler/logging.go
> +			slog.Any("payload", payload),
@dborovcanin should we log payload?

2024-01-22 11:10 UTC, rodneyosodo commented on pkg/messaging/handler/logging.go
> +		args := []interface{}{
Use this approach to keep your code DRY https://github.com/absmach/mproxy/blob/695f58d860bd1c588e106c9ad679a9cfb9b69dd2/examples/simple/simple.go#L70

2024-01-22 13:02 UTC, dborovcanin commented on pkg/messaging/handler/logging.go
> +			slog.Any("payload", payload),
No, let's not log the payload. @Musilah

2024-01-22 13:08 UTC, dborovcanin commented on pkg/messaging/handler/logging.go
> +		args := []interface{}{
This is correct only in case we do repeat a lot, i.e. we use a lot of the same attributes. I suspect that is the case, but there might be some services where it is not, so @Musilah be careful. The logging utility func should not include a lot (tule of the thumb - more than 5) of cases.

2024-01-23 08:21 UTC, rodneyosodo requested changes
Some packages have not been updated for example `consumers/writers/api/logging.go`

2024-01-23 08:21 UTC, rodneyosodo commented on auth/api/logging.go
> +			slog.Any("limit", limit),
Use int64 and use type conversion

2024-01-23 08:21 UTC, rodneyosodo commented on auth/api/logging.go
> +			slog.String("duration", time.Since(begin).String()),
Add more keys same as other scenarios in this package

2024-01-23 08:21 UTC, rodneyosodo commented on bootstrap/api/logging.go
> +			lm.logger.Warn("Add failed to complete successfully", args...)
Add more context to this log. What are we adding?. Have a look at this comment and implement is for all services https://github.com/absmach/magistrala-old/pull/272#pullrequestreview-1836173646

2024-01-23 08:21 UTC, rodneyosodo commented on certs/api/logging.go
> +			lm.logger.Warn("List serials failed to complete successfully", args...)
```suggestion
			lm.logger.Warn("List certificate serials failed to complete successfully", args...)
```

2024-01-23 08:21 UTC, rodneyosodo commented on coap/api/logging.go
> +		}
```go
		args := []interface{}{
			slog.String("duration", time.Since(begin).String()),
			slog.String("channel_id", msg.GetChannel()),
		}
		if msg.GetSubtopic() != "" {
			args = append(args, slog.String("subtopic", msg.GetSubtopic()))
		}
```

2024-01-23 08:21 UTC, rodneyosodo commented on consumers/notifiers/api/logging.go
> +				"page_metadata",
```suggestion
				"page",
```

Same as other cases

2024-01-23 08:21 UTC, rodneyosodo commented on lora/api/logging.go
> +				slog.String("thing_id", thingID),
```suggestion
				slog.String("id", thingID),
```

2024-01-23 08:21 UTC, rodneyosodo commented on lora/api/logging.go
> +				slog.String("lora_dev_eui", loraDevEUI),
```suggestion
				slog.String("dev_eui", loraDevEUI),
```

2024-01-23 08:21 UTC, rodneyosodo commented on lora/api/logging.go
> +				slog.String("thing_id", thingID),
Same as other cases

2024-01-23 08:21 UTC, rodneyosodo commented on lora/api/logging.go
> +				slog.String("lora_dev_eui", loraDevEUI),
Same as other cases

2024-01-23 10:51 UTC, rodneyosodo requested changes

2024-01-23 10:51 UTC, rodneyosodo commented on auth/api/logging.go
> +				"object",
When you do a list objects you are expecting and object so this will be empty. You use subject to list objects

```go
args := []interface{}{
	slog.String("duration", time.Since(begin).String()),
	slog.Group(
		"object",
		slog.String("type", pr.ObjectType),
	),
	slog.Group(
		"subject",
		slog.String("id", pr.Subject),
		slog.String("type", pr.SubjectType),
	),
	slog.String("permission", pr.Permission),
}
```

2024-01-23 10:51 UTC, rodneyosodo commented on auth/api/logging.go
> +			slog.Group(
```go
args := []interface{}{
	slog.String("duration", time.Since(begin).String()),
	slog.Group(
		"subject",
		slog.String("type", pr.SubjectType),
	),
	slog.Group(
		"object",
		slog.String("id", pr.Object),
		slog.String("type", pr.ObjectType),
	),
	slog.String("permission", pr.Permission),
}
```

2024-01-23 10:54 UTC, rodneyosodo requested changes

2024-01-23 10:54 UTC, rodneyosodo commented on auth/api/logging.go
> +			slog.Any("filter_permissions", filterPermissions),
```go
args := []interface{}{
	slog.String("duration", time.Since(begin).String()),
	slog.Any("filter_permissions", filterPermissions),
	slog.Group(
		"object",
		slog.String("id", pr.Object),
		slog.String("type", pr.ObjectType),
	),
	slog.Group(
		"subject",
		slog.String("id", pr.Subject),
		slog.String("type", pr.SubjectType),
	),
}
```

2024-01-23 10:54 UTC, rodneyosodo commented on auth/api/logging.go
> +			slog.String("relation", pr.Relation),
Use permission

2024-01-23 10:54 UTC, rodneyosodo commented on auth/api/logging.go
> +			slog.String("duration", time.Since(begin).String()),
```go
args := []interface{}{
	slog.String("duration", time.Since(begin).String()),
	slog.Group(
		"object",
		slog.String("id", pr.Object),
		slog.String("type", pr.ObjectType),
	),
	slog.Group(
		"subject",
		slog.String("id", pr.Subject),
		slog.String("type", pr.SubjectType),
	),
	slog.String("permission", pr.Permission),
}
```

2024-01-24 10:08 UTC, dborovcanin requested changes

2024-01-24 10:08 UTC, dborovcanin commented on auth/api/logging.go
> +				slog.String("type", pr.SubjectType),
Let's flatten Policy by using a single Group here, like:
```suggestion
			slog.Group(
				"policy_request",
				slog.String("object_type", pr.ObjectType),
				slog.String("subject_id", pr.Subject),
				slog.String("subject_type", pr.SubjectType))
```

2024-01-24 11:33 UTC, dborovcanin approved these changes

2024-01-24 12:14 UTC, rodneyosodo requested changes

2024-01-24 12:14 UTC, rodneyosodo commented on certs/api/logging.go
> +		lm.logger.Info("List certificates completed successfully", args...)
```suggestion
		lm.logger.Info("List certificates serials completed successfully", args...)
```

2024-01-24 12:14 UTC, rodneyosodo commented on certs/api/logging.go
> +				slog.Uint64("limit", cp.Limit),
Add total

2024-01-24 12:14 UTC, rodneyosodo commented on bootstrap/api/logging.go
> +			slog.String("id", id),
```suggestion
			slog.String("thing_id", id),
```

Also add connections

2024-01-24 12:14 UTC, rodneyosodo commented on bootstrap/api/logging.go
> +			slog.String("id", id),
```suggestion
			slog.String("channel_id", id),
```

2024-01-24 16:43 UTC, rodneyosodo approved these changes

2024-01-24 16:59 UTC, dborovcanin commented on auth/api/logging.go
> +				slog.String("id", pr.Subject),
We need to make this user ID, rather than the token. Let's open a ticket for this, it's out of the scope for this PR.

2024-01-24 17:01 UTC, dborovcanin approved these changes

2024-01-24 17:01 UTC, merged