NOISSUE - Simplify docker deployment
absmach/magistrala-old pull request #275
Opened 2024-01-19 14:39 UTC by rodneyosodo

# What type of PR is this?

This is an optimization because it improves docker-compose deployment

## What does this do?

It simplifies docker-compose deployment to use one configuration where nats is used as the MQTT broker, Message Broker and Events Store.

## Which issue(s) does this PR fix/relate to?

No issue

## Have you included tests for your changes?

Yes, I have tested it manually

## Did you document any new/modified feature?

Yes, I have added documentation about the deployment

### Notes

2024-01-22 01:08 UTC, arvindh123 commented on docker/README.md
> +    environment:
We can add `container_name` for this example.

2024-01-22 01:35 UTC, arvindh123 commented
@rodneyosodo 
In `.env` file 
we have at present for ES we have :
```env 
MG_ES_TYPE=${MG_MESSAGE_BROKER_TYPE}
MG_ES_URL=${MG_NATS_URL}
```

Instead having  `${MG_MESSAGE_BROKER_TYPE}` value for env varabile`MG_ES_TYPE` , Can we have `MG_ES_TYPE` value as `nats`/`redis`,like given below
```env
MG_ES_TYPE=nats
MG_ES_URL=${MG_NATS_URL}
```

2024-01-23 09:38 UTC, rodneyosodo commented
For now, the Event Store depends on the Message broker apart from when it is Redis. I have changed the env file to reference `MG_MESSAGE_BROKER_*` and documented when it is redis

2024-01-23 09:50 UTC, ianmuchyri commented on docker/README.md
> +Since nats is used as both MQTT_BROKER and MESSAGE_BROKER, it is not possible to run nats as an MQTT_BROKER and nats as a MESSAGE_BROKER at the same time, this is the current depolyment strategy for
I don't quite understand this statement. It's used as both MQTT and message broker but, it's not possible to run it as a MQTT and message broker simultaneously. Isn't that contradicting?

2024-01-23 11:07 UTC, ianmuchyri commented on docker/README.md
> +2. MESSAGE_BROKER: Manages communication between adapters and Magistrala writer services. This can either be 'nats' or 'rabbitmq' or 'redis'. This is used to store messages for distributed processing
```suggestion
2. MESSAGE_BROKER: Manages communication between adapters and Magistrala writer services. This can either be 'nats' or 'rabbitmq'. This is used to store messages for distributed processing.
```

In the next paragraph you say redis cannot be used as message broker

2024-01-23 11:11 UTC, ianmuchyri commented on docker/README.md
> +```env
no need for this one, as it it in the one below

2024-01-23 11:11 UTC, ianmuchyri commented on docker/README.md
> +MG_ES_TYPE=redis MG_MESSAGE_BROKER_TYPE=rabbitmq make dockers
no need for this one too

2024-01-23 12:27 UTC, rodneyosodo commented on docker/README.md
> +```env
https://github.com/DavidAnson/markdownlint/blob/v0.31.1/doc/md040.md

2024-01-26 10:23 UTC, arvindh123 commented on docker/README.md
> +```env
It is command passing with varabiles, So it can be bash, sh or anyother

2024-01-29 10:07 UTC, dborovcanin requested changes

2024-01-29 10:07 UTC, dborovcanin commented on docker/README.md
> +Events store: This is the same as MESSAGE_BROKER. This can either be 'NATS' or 'RabbitMQ' or 'Redis'. This is used by Magistrala services to store events for distributed processing. If Redis is used
Replace with something like: `By default, we are using the same broker for messages and events.` You can also remove it since it's already mentioned above.

2024-01-29 10:07 UTC, dborovcanin commented on docker/README.md
> +2. MESSAGE_BROKER: Manages communication between adapters and Magistrala writer services. This can either be 'NATS' or 'RabbitMQ. This is used to store messages for distributed processing.
It's not only writers but any internal consumer. `Manages message exchange between Mainflux core, optional, and external components.`

2024-01-29 10:07 UTC, dborovcanin commented on docker/README.md
> +For MQTT broker other than NATS, you would need to change the `docker/.env`. For example, to use VerneMQ as a MQTT broker:
Make VerneMQ a default MQTT broker.

2024-01-29 12:37 UTC, dborovcanin approved these changes

2024-01-29 15:53 UTC, merged