NOISSUE - Remove `TestUnavailablePublish` due to Uncertainties
absmach/magistrala-old pull request #277
Opened 2024-01-23 13:35 UTC by rodneyosodo

# What type of PR is this?

This is a bug fix because it fixes failing tests for events package

## What does this do?

Removes TestUnavailablePublish due to uncertainty when running tests on CI. It also removes the code to generate random events, spawn goroutines for publishing, and test unavailable publish when the message broker is unreachable.

## Which issue(s) does this PR fix/relate to?

No issue

## Have you included tests for your changes?

Yes, I have included tests for my changes.

## Did you document any new/modified feature?

No

### Notes

2024-01-24 10:53 UTC, dborovcanin requested changes
Did you try to spawn fewer routines (say, 100, instead of 1m), and wait shorter (say, 3s instead of 1m)? Also, consider replacing simple wait with the actual consumer (while this will definitely make this test even more "integration") so that we wait for all the events to be consumed properly.

2024-01-25 12:36 UTC, dborovcanin requested changes

2024-01-25 12:36 UTC, dborovcanin commented on pkg/events/redis/publisher.go
> +func NewPublisher(ctx context.Context, url, stream string, unpublishedEventsCheckInterval time.Duration) (events.Publisher, error) {
Rename to `retryPeriod` or just `retry` - `time.Duration` type implies the purpose.

2024-01-25 12:36 UTC, dborovcanin commented on pkg/events/redis/publisher.go
> +// startPublishingRoutine periodically checks the Redis connection and publishes
Rename to `flushUnpublished` or something similar.

2024-01-25 12:36 UTC, dborovcanin commented on pkg/events/redis/publisher.go
> +			if err := es.checkConnection(ctx); err == nil {
Any reason for reversing the order here?

2024-01-25 13:21 UTC, rodneyosodo commented on pkg/events/redis/publisher.go
> +			if err := es.checkConnection(ctx); err == nil {
The order hasn't changed only renaming

2024-01-25 14:43 UTC, dborovcanin commented on pkg/events/redis/publisher.go
> +			if err := es.checkConnection(ctx); err == nil {
I meant, [on the line below](https://github.com/absmach/magistrala-old/blob/867060f6a5c76d4cf8f8dbe632da76283896cd63/pkg/events/redis/publisher.go#L85); we use reverse order to publish events. Is there a reason we use reverse order?

2024-01-25 15:02 UTC, dborovcanin approved these changes

2024-01-25 15:02 UTC, merged

2024-01-25 15:11 UTC, rodneyosodo commented on pkg/events/redis/publisher.go
> +			if err := es.checkConnection(ctx); err == nil {
First event published will be the first event to be republished